### ISSUE TITLE
worker thread hangs for micropip

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#14]
here is an example of polyscript + worker.  Things starts to hang in definitely when it gets to micropip.install in the worker thread for some reason.  https://b412faf3-21af-4adc-894d-6174cf4f38a6.pyscriptapps.com/9c92b15a-2412-4d76-a09a-f39912726b5a/latest/

**Comment by WebReflection** [comment]
beside the fact I see everything just fine:

![Screenshot from 2023-08-21 10-42-47](https://github.com/pyscript/polyscript/assets/85749/250b3813-7adf-4308-9766-42fdd07a6d3c)

it's not clear to me what you are doing there or why things are done that way ... you can just have polyscript on the page and use:

```html
<script type="pyodide" worker="./worker.py" config='{"packages":["matplotlib","seaborn","pandas"]}' async></script>
```

in worker you have access to the main thread DOM via `from polyscript import window` and then `document = window.document`.

There is a mix of pyscript stuff and `<script type="py">` on the page without latest pyscript loaded neither, where things would be even simpler as you have `from pyscript import document, sync` there and the `worker="./file.py"` attribute also would work without needing to evaluate anything.

So, until intent, expectations, and actually issues are understood, I am afraid it's hard to help out or fix anything, in case it needs to be fixed.

Thanks in advance for helping out to help you out.

**Comment by bugzpodder** [comment]
@WebReflection so on pyscript.com proper, it runs on main-thread and everything works as expected, the reason is that crossOriginIsolated is false (I have not attempted your `<script type="pyodide" worker="./worker.py">`).
If you click on my [link](https://b412faf3-21af-4adc-894d-6174cf4f38a6.pyscriptapps.com/9c92b15a-2412-4d76-a09a-f39912726b5a/latest/) it runs in the worker.    Check out my [bootstrap](https://b412faf3-21af-4adc-894d-6174cf4f38a6.pyscriptapps.com/9c92b15a-2412-4d76-a09a-f39912726b5a/latest/bootstrap.js) script which checks crossOriginIsolated and runs things in a worker.  I have a div that says if it runs on main thread vs worker, and you'll see something like this:

<img width="1024" alt="Screenshot 2023-08-21 at 12 11 36 PM" src="https://github.com/pyscript/polyscript/assets/14841421/7fa048ae-69cc-46a8-8eaa-7441dc0d5280">


> it's not clear to me what you are doing there or why things are done that way ... you can just have polyscript on the page and use: `<script type="pyodide" worker="./worker.py" ...`

Agreed that this works for a typical pyscript/polyscript user where they are playing with a static html page.  I currently use this is a React application where the code blocks are stored in a sql database and loaded via a python endpoint.  I think the biggest difference is that a) React doesn't work well with web-components, and b) there is a lot of dynamic runtime issues involved where I need to control the execution lifetime such as dealing with running code on demand, bootstraping dataframe inputs and error handling.  fortunately i have all of this sorted out.

> There is a mix of pyscript stuff and <script type="py"> on the page without latest pyscript loaded neither, where things would be even simpler as you have from pyscript import document, sync there and the worker="./file.py" attribute also would work without needing to evaluate anything.

There is probably room for improvement but thats what's working for me.  I did need to my code to work in both crossOriginIsolated = true and crossOriginIsolated = false environments so thats where the most of the complexity comes from.  I also need things to run only when requested since I don't want to bootstrap the worker until I am ready to run the script for example.

>So, until intent, expectations, and actually issues are understood, I am afraid it's hard to help out or fix anything, in case it needs to be fixed.

Understood.  I don't actually need anything fixed right now since the main thread works for me and worker doesn't so I will continue to run things on the main thread until this worker issue gets resolved.

That being said I am not doing anything special in the worker, it is very strange that micropip.install doesn't work on worker thread and its consistently reproducible.   It's also almost the exact same code as 
```<script type="pyodide" worker="./worker.py" config='{"packages":["matplotlib","seaborn","pandas"]}' async></script>``` is doing behind the scene so why does it work when you specify the packages in config but not when you use xworker.sync?

**Comment by WebReflection** [comment]
> React doesn't work well with web-components

polyscript doesn't use Custom Elements, and if you have no pyscript library loaded, your `<script type="py">` does nothing there in polyscript, as PyScript is a custom type of polyscript.

> I don't want to bootstrap the worker until I am ready to run the script for example.

this makes little sense to me ... you can always bootstrap a worker and actually the sooner the better for perceived performance, specially if there are dependencies.

> it is very strange that micropip.install doesn't work on worker thread and its consistently reproducible

it does work out of all live examples we have but it's the polyscript bootstrap that does that .. you pass your toml, polyscript does the rest. What doesn't work to you is your way to load packages ... polyscript workers are already tested and work without issues, that's why I said it's hard to reproduce or understand the issue here ... you're doing things in a weird way not documented, nor suggested, anywhere .. you never want to install packages manually in a worker, when you have a toml, I hope this makes sense.

> if there is an alternative way of installing additional packages for pyodide in worker

I think that should work but not from main ... what's in Workers stay in workers, and vice-versa, but I think you understand this already.

> I think it's a bug with https://github.com/WebReflection/coincident maybe?

that project knows nothing about python, pyodide, micropython, or anything else ... it just orchestrates Atomics between workers and main and it's very unlikely it can ever cause issues at the network level, unless proven otherwise with an example.

I think I could work on something if you could provide the bare minimal example that fails dropping any 3rd party library/indirection so that I am sure I know what I am looking at ... so far it's not clear at all to me, and the fact network issues/bugs have been filed doesn't make me confident there's something at all to work on in here.

Thanks for your patience, I really want React being able to use PyScript and/or Polyscript, but I need to understand what to eventually fix or change.

**Comment by bugzpodder** [comment]
> polyscript doesn't use Custom Elements, and if you have no pyscript library loaded, your `<script type="py">` does nothing there in polyscript, as PyScript is a custom type of polyscript.
> this makes little sense to me ... you can always bootstrap a worker and actually the sooner the better for perceived performance, specially if there are dependencies.

Right but I don't just want to inject a <script type="py"> into my entire app since only a small part of it uses python scripts.  Currently I do load [polyscript/pyscript.js](https://unpkg.com/browse/polyscript@0.1.1/pyscript.js) so if i do have a script type=py tag it will load pyodide immediately.  I resorted to dynamically insert this tag before execution.
Hence I just want to bootstrap pyodide and large packages (like plotly) only when we are showing a view where pyodide is needed to execute some custom code.

> I think I could work on something if you could provide the bare minimal example that fails dropping any 3rd party library/indirection so that I am sure I know what I am looking at ... so far it's not clear at all to me, and the fact network issues/bugs have been filed doesn't make me confident there's something at all to work on in here.
> 

The repo example is this:
https://b412faf3-21af-4adc-894d-6174cf4f38a6.pyscriptapps.com/9c92b15a-2412-4d76-a09a-f39912726b5a/latest/

it's about 50 lines of code between bootstrap.js and worker.py so it should easily be workable.  But happy to trim it down if needed.  Just another note: Do not load this link in any other way (like on pyscript.com) as crossOriginIsolated is not set there and it only repos when you click on this link directly.  You should see "installing packages in worker" and a blank page (ie it fails to install stuff in worker)

This example repos consistently as the worker fails to install the requested packages every time.  Let me know if you see a graph (that means its working for you)

**Comment by JeffersGlass** [comment]
>  you're doing things in a weird way not documented, nor suggested, anywhere .. you never want to install packages manually in a worker, when you have a toml, I hope this makes sense.

Installing via micropip is the standard way to install packages in Pyodide, and is documented in the [micropip documentation](https://micropip.pyodide.org/en/stable/project/usage.html). It works in 'naked' Pyodide, and on the main thread in PolyScript+Pyodide. It's not unreasonable to _expect_ it to work in the worker as well - if there's something that works in Pyodide but doesn't work in Pyodide-in-Polyscript (i.e. PyScript), we should investigate why and either fix it or document the differences.

**Comment by bugzpodder** [comment]
@JeffersGlass does my repo example work for you? Do you see a graph when running the code in a worker [here](https://b412faf3-21af-4adc-894d-6174cf4f38a6.pyscriptapps.com/9c92b15a-2412-4d76-a09a-f39912726b5a/latest/)?

In terms of micropip I found several issues which may or may not be related:
1. micropip times out when getting manifest from pypi (eg https://pypi.org/pypi/seaborn/json)
2. micropip fetches manifest successfully but hangs when installing the package into the virtual fs
3. micropip doesn't even get called because of an issue with xworker.sync.  This is what this issue attempts to cover and at least from this example it repos consistently.  The previous two issues needs more investigation in terms of whether it is a browser/worker/micropip/pyodide/polyscript issue (or whether it only happens to me).

**Comment by bugzpodder** [comment]
@WebReflection found one issue: if a function doesn't exist
```
await xworker.sync.doesntexist()
```
will hang forever

**Comment by JeffersGlass** [comment]
@bugzpodder No I see no graph when I go to that link. As you say earlier, when I view that app on PyScript.com proper, the graph does appear, but I gather that's expected and not part of the error.

**Comment by WebReflection** [comment]
@JeffersGlass what I meant is that we have docs and examples to bootstrap packages at the right time during pyodide initialization both on main and workers and that works. If that way was used and there was an issue then I could dig more into the code. If other ways are used then I can’t easily dig into pyodide so it’s harder to understand what’s going on.

@bugzpodder now that’s something I can fix/work on, but it doesn’t seem to be related to this issue, as your code runs in an env and not in another. I start believing this is indeed a headers issue but I need to dig more into your demo. I’m on vacation these days so apologies for not putting the right amount of effort this issue deserves, I just want to be sure I fully understand the issue to work properly on it next week once I’m back.

**Comment by WebReflection** [comment]
@bugzpodder another thing about PyScript is that it includes already polyscript so having both leads to double bootstrap of polyscript logic and that might cause unexplored issues. I don’t want to leak on the global scope a flag but most importantly polyscript in PyScript needs to handle PyScript things so using both on the same page should be flagged as error. If you just import PyScript you can still use polyscript out of the box so maybe that would solve already some gotcha?

**Comment by WebReflection** [comment]
I read this reply oddly … some extra new line might help but I think I got what you replied so I’ll have a better look and definitely the forever pending await on missing methods in sync will be solved somehow in coincident module, still that won’t probably solve this issue, but maybe it can help debugging.

**Comment by WebReflection** [comment]
@bugzpodder ... about this:

> if a function doesn't exist await it will hang forever.

I am afraid after investigating your issue that's not what happens at all ... and there's no way to fix that specific use case if not by improving documentation around it, as it surprised me too until the *A-HA* moment.

This is how Atomics work:

  * the worker uses a proxy trap that is forwarded to the main to execute a method
    * the worker is **completely blocked** until that method returns ... this is the beauty of making *async* code *sync* through a worker ... however ...
  * the main execute the function that can be either sync or async ... pretty irrelevant as the dance is inevitably *async* anyway
    * while executing the function, the worker cannot possibly react to anything because it on hold until the main function has exited
    * accordingly, if you await in main a worker function within a function that the worker is awaiting you create a **deadlock** because while the worker is paused to be notified on the main function, the function await the worker to be responsive

The easy solution is to actually **don't await** worker utilities within a function exposed to the worker, so that your example would be instead (as example):

```js
// exposed in the main .sync
xworker.sync.main = () => {
  // exposed in the worker .sync
  xworker.sync.worker().then(console.log);
};
```

doing that you'll either read an error that `worker` as method is not defined so it cannot be invoked or you will receive the result of that call once the worker is not busy anymore.

**Please Note**
A possible solution in *coincident* could be to flag internally the fact a sync callback is being executed and any invoke to the `sync` proxy itself can't be done ... however, this would remove the ability to still invoke that function just not while awaiting so I believe the best thing to do is to improve documentation around this topic but also I'll try to find out if there's a way to at least show an error in case this situation happens as forever hanging while doing nothing programs don't look like a great deal to me.

All of this still has not much to do with the issue described in this page, if I am not mistaken.

**Comment by bugzpodder** [comment]
I tested it out the proposed solution and it works.  Thanks.

**Comment by WebReflection** [comment]
@bugzpodder I've updated *coincident* which now shows at least a warning around possible seppuku, still letting you invoke proxied methods without `await` as the suggested workaround indeed worked for you.

`await` implicitly reaches `clalback().then` so we can't distinguish between `await` as syntax and you reaching `then()` manually but **at least** now it's clear in console what is going on, discouraging the usage of remote proxied methods while executing a main method.

I hope this is reasonable and fine to you.
