### ISSUE TITLE
defined/whenDefined only works with script tag (main thread)

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#17]
example: https://pyscript.com/@bugzpodder/patient-sky/latest

In html I don't have:
```<script type="py"></script>```
So define doesn't do anything.

I need to inject this tag `<script type="py"></script>` into my dom in order for polyscript to work in main thread.  WebR/XWorker doesn't have this issue and I'd prefer not to do this.

**Comment by WebReflection** [comment]
I am not sure what you're after here ... `define` and `whenDefined` are for custom tags ... and the primitive `PyScript` is based on to define itself ... if you don't need a custom type, don't use it ...

**Comment by WebReflection** [comment]
to clarify:

> I need to inject this tag <script type="py"></script> into my dom in order for polyscript to work in main thread. 

polyscript works without `type="py"` becaus eit knows nothing about `type="py"` ... polyscript is the core behind PyScript which uses `define` to declar itself ... maybe you are confused about the goal of this repo/project ... this is **not PyScript**, this is the primitive PyScript uses to work itself.

**Comment by WebReflection** [comment]
looking at your example, polyscript doesn't know anything about py-config neither ... I think you might want to start using `@pyscript/core` module instead as your expectations are all about `type="py"` which means nothing in here ... am I correct?

**Comment by bugzpodder** [comment]
Yes I understand the differentiation between polyscript and pyscript, and I have a production app running with real code.

My goal is to not deal with any of the `<script type="py">` in my app because it is a react app.  As an example (all of this is real code as I just copy/paste from my production app codebase):

WebR:
```
import { WebR } from "webr";
export async function exec(input: string) {
  const webR: WebR = new WebR();
  await webR.init();
  return  webR.evalRVoid(code);
```

XWorker:
```
import { XWorker } from "polyscript";
const options = {
  type: "pyodide",
};
const pyworker = new XWorker("/pyscript/worker.py", options);
```

how do I run code in main thread without defining a `<script type="py">`

**Comment by WebReflection** [comment]
that's odd ... polyscript has no script `type="py"` in its source code ... I am not sure what you are running there, which is why I mentioned drop your own bootstrap logic to help me help you ... that being said:

> how do I run code in main thread without defining a <script type="py">

check examples in docs, as nothing uses `<script type="py">` there .... `<script type="pyodide">` is your entry point for pyodide in main, `<script type="micropython">` an alternative too ... there is no `<script type="py">` in here, so I think all issues showing that as reason for the issue will be closed, as the `type="py"` is **not** this repository business.

**Comment by bugzpodder** [comment]
I mispoke.  My code is:
```
    import('https://esm.sh/polyscript@0.1.10').then(polyscript => {
        polyscript.define("py2", { interpreter: "pyodide", async onInterpreterReady(pyScript) {
            ... // won't trigger
        } });
        
    });
```
However onInterpreterReady won't trigger without an additional `<script type="py2"></script>`
Hopefully there is a way to get around this without defining the script tag.

**Comment by WebReflection** [comment]
@bugzpodder that's intentional as lazy-load behavior, which is also how custom elements work, the API `define` and `whenDefined` mimic. As workaround, your code could simply bootstrap the script and drop it once ready.

A script on the page, or a custom element, is needed because of the `target` resolution when you use `display` and you don't specify a target. The target could be used further to show errors, when desired, in the place errors happened (the related script or custom element, to make errors contextual).

A script on the page doesn't affect performance, doesn't block neither (thanks to custom type), it's invisible for both the browser and the user, it's up to you to remove it once ready, but you have this freedom.

```js
     import('https://esm.sh/polyscript@0.1.10').then(polyscript => {
        polyscript.define("my-py", { interpreter: "pyodide", async onInterpreterReady(pyScript) {
            // you have it bootstrapped
            // ... and if you want to, or need to ...
            script.remove();
        } });
        const script = Object.assign(document.createElement('script'), {type: 'my-py'});
        document.head.append(script); // or document.body, you chose
    });
```

**Comment by WebReflection** [comment]
P.S. before anyone asks, we **cannot** bootstrap interpreters on `define` because if there is nothing on the page to evaluate it makes no sense to have *pyodide* bootstrapped out of the box in the main thread ... so this request won't happen because it means it'll block every *pyscript* page, even if the script explicitly uses a worker to avoid blocking the main on bootstrap.

The only acceptable request is to provide a different API that exposes only the interpreter but as that's trivial to do when/if desired, as shown in my previous example code, and as we don't have well defined use cases for this, I don't find it particularly urgent to do and we're planning to release next week pyscript in main.

**Comment by bugzpodder** [comment]
> A script on the page doesn't affect performance, doesn't block neither (thanks to custom type), it's invisible for both the browser and the user, it's up to you to remove it once ready, but you have this freedom.

Agreed.  This is what I do today.  However it just gives a better developer experience if polyscript supports bootstrapping via a traditional JS class or function call.

> P.S. before anyone asks, we cannot bootstrap interpreters on define because if there is nothing on the page to evaluate it makes no sense to have pyodide bootstrapped out of the box in the main thread.

It makes sense for pyscript.  However in what situations would user dynamically inject code blocks into the page later?  The only case I can think of is after user interaction with the page.

For example: page loads -> polyscript bootstraps -> user clicks on something -> `script type="..."` gets injected -> pyodide gets bootstraped etc.

> as shown in my previous example code, and as we don't have well defined use cases for this, I don't find it particularly urgent to do and we're planning to release next week pyscript in main.

None of my requests are urgent in any way, i have different workarounds in place.

**Comment by WebReflection** [comment]
> It makes sense for pyscript. However in what situations would user dynamically inject code blocks into the page later?

if you have a `<script type="py" worker="./file.py"></script>` you never want pyodide to bootstrap on the main page and this is mandatory for the project and requested as feature.

**Comment by WebReflection** [comment]
> This is not for the worker, this is for the main thread

if you have a `<script type="py" worker="...">` you don't want ever to have the page blocked on the main ... we won't block on the main out of the box, that's not necessary, not desired, not needed ... the best we can offer is a function to bootstrap an interpreter for you, but PyScript use case is clear and it requires either scripts on the main with Python code, or scripts that will run on the worker *without* blocking ever the main, if no script is there. That's what `define` does ... it handles scripts / custom elements. If you don't want that, that's another matter, not what `define` should do.

**Comment by bugzpodder** [comment]
> if you have a <script type="py" worker="..."> you don't want ever to have the page blocked on the main 

Right but I am saying I don't want to use a worker in this case, just want to run it on the main thread.

> P.S. one thing that might work is to provide a flag that ignores the DOM and just bootstrap ... but it feels a bit of a stretch from the DOM related define API.

Yeah I would prefer not deal with the DOM and basically do want a new API.  But this is not available right now and thats why define is used.  The new API basically works the same as XWorker but for main thread.

**Comment by WebReflection** [comment]
@bugzpodder would [this work](https://github.com/pyscript/polyscript/pull/22) ?

it basically allows you to `define(null, { ...config })` without branching the logic too much, offering all hooks and same things any `define` offer already, dropping the script so no target exists out of the box and no leaks happen in the internal registry.

**Comment by bugzpodder** [comment]
nice, yeah thats great.

**Comment by WebReflection** [comment]
> nice, yeah thats great.

it's up and running
