### ISSUE TITLE
cannot read non-functions in python worker

### ISSUE THREAD

**Issue by bugzpodder** [pyscript/polyscript#29]
main thread (works): https://pyscript.com/@bugzpodder/xworker-sync-access-js-vals-copy/latest
worker (not working): https://bugzpodder.pyscriptapps.com/xworker-sync-access-js-vals-copy/latest/

basically, in js land I am passing in some stuff via: xworker.sync.foo = 'abc'
it doesn't seem like I can pull them out in python
functions works fine
I'm interested in getting all attributes defined on xworker.sync but unable to do this as well.

My workaround is to declare a function to pass it in and it will return whatever I need.

**Comment by WebReflection** [comment]
sync is a proxy, all things are discovered lazy and at runtime. Sync also is, by design, for functions: you invoke one and pass zero or more arguments, you get a result. Create your own method to return a list of sync utilities, as you define these yourself, right?

**Comment by WebReflection** [comment]
P.S. this has low to zero priority these days due release coming

**Comment by bugzpodder** [comment]
fair enough, i'm fine with only supporting functions.

**Comment by WebReflection** [comment]
If it’s worth adding anything, sync as properties has design issues because it can’t be (easily) observed cross realms … it’s kept simple on purpose to serve patches for foreign PLs and all use cases right now are targeting functions, not accessors (getters). As functions can work both to invoke utilities or retrieve data, like accessors (getters), that felt good enough for most use cases. Accessors work out of window proxies though, but that’s a different use case / pattern all together. I’m not saying coincident could be smarter for sync, but I need a very strong reason to make sync more complex.

**Comment by bugzpodder** [comment]
sg.  Is xworker.window a special thing then?

**Comment by WebReflection** [comment]
it's a whole Proxy with a completely different orchestration behind the scene.

[this is coincident](https://github.com/WebReflection/coincident/blob/main/esm/index.js#L57-L106) ... by design, docs, and API, it allows you to define a **callback** either in the main or the worker thread.

[this is coincident/window](https://github.com/WebReflection/coincident/tree/main/esm/shared) which is a completely different orchestration to offer 1:1 usage from a worker.
